# Generated by Django 4.2.11 on 2024-03-27 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('state', models.CharField(max_length=255, verbose_name='Штат')),
                ('zip_code', models.CharField(max_length=255, unique=True, verbose_name='Почтовый индекс')),
                ('geo_lat', models.DecimalField(db_index=True, decimal_places=16, max_digits=19, verbose_name='Широта')),
                ('geo_lon', models.DecimalField(db_index=True, decimal_places=16, max_digits=19, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Вес')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('delivery_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_delivery', to='service_delivery.location', to_field='zip_code', verbose_name='Локация доставки')),
                ('pick_up_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_pick_up', to='service_delivery.location', to_field='zip_code', verbose_name='Локация pick-up')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='цифра 1000-9999+заглавная буква английского алфавита', regex='^\\d{4}[A-Z]$')], verbose_name='Уникальный номер')),
                ('lift_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъемность')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='service_delivery.location', to_field='zip_code', verbose_name='Текущая локация')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
