# Generated by Django 4.2.1 on 2024-03-29 19:50

from django.db import migrations
from scripts.load_cars import run


class Migration(migrations.Migration):

    dependencies = [
        ("service_delivery", "load_location"),
    ]

    def load_data(apps, schema_editor):

        run()

    operations = [
        migrations.RunPython(load_data),
    ]
